---
apiVersion: v1
kind: Service
metadata:
  namespace: example
  name: example-mongodb-primary-0
  labels:
    name: example-mongodb-primary-0
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: example-mongodb-primary-0
  ports:
    - name: mongo
      port: 27017
      nodePort: 31001
      protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  namespace: example
  name: example-mongodb-secondary-0
  labels:
    name: example-mongodb-secondary-0
spec:
  type: NodePort
  selector:
    name: example-mongodb-secondary-0
  ports: 
    - name: mongo
      port: 27017
      nodePort: 31002
      protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  namespace: example
  name: example-mongodb-secondary-1
  labels:
    name: example-mongodb-secondary-1
spec:
  type: NodePort  
  selector:
    name: example-mongodb-secondary-1
  ports: 
    - name: mongo
      port: 27017
      nodePort: 31003
      protocol: TCP