---
apiVersion: v1
kind: Service
metadata:
  name: example-mongo-headless
  namespace: example
  labels:
    name: example-mongo-headless
spec:
  clusterIP: None
  ports:
  - name: mongo
    port: 27017
  selector:
    role: mongo-proxy