apiVersion: v1
kind: Pod
metadata:
  namespace: example
  name: example-mongodb-primary-0
  labels:
    name: example-mongodb-primary-0
    role: mongo-proxy
spec:
  terminationGracePeriodSeconds: 10
  hostname: example-mongodb-primary-0
  subdomain: example-mongodb-headless
  containers:
  - name: nginx-proxy
    image: nginx:latest
    ports:
    - name: mongo
      containerPort: 27017
    volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx/
  volumes:
    - name: config-volume
      configMap:
        name: cm-nginx-proxy-mongo-p-0
  restartPolicy: Never